version: 2

sources:
  - name: staging_historic
    database: de-zoom-final
    schema: wildfires_historic_dataset
    tables:
      - name: historic
  
  - name: staging_active
    database: de-zoom-final
    schema: wildfires_active_dataset
    tables:
      - name: active

models: 
  - name: stg_staging__active
    description: "Active wildfires in Canada"
    columns:
      - name: agency
        description: "The agency responsible for the fire"
        data_type: STRING
      - name: fire_name
        description: "Name of the fire"
        data_type: STRING
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn
      - name: lat
        description: "Latitude of the fire location"
        data_type: FLOAT
        tests:
          - not_null:
              severity: warn
      - name: lon
        description: "Longitude of the fire location"
        data_type: FLOAT
        tests:
          - not_null:
              severity: warn
      - name: startdate
        description: "Start date of the fire"
        data_type: STRING
      - name: hectares
        description: "Area affected by the fire in hectares"
        data_type: FLOAT
        tests:
          - not_null:
              severity: warn
      - name: stage_of_control
        description: "Stage of control of the fire"
        data_type: STRING
      - name: timezone
        description: "Timezone of the fire location"
        data_type: STRING
      - name: response_type
        description: "Type of response to the fire"
        data_type: STRING
  
  - name: stg_staging__historic
    description: ""
    columns:
      - name: fire_id
        data_type: string
        description: ""

      - name: fire_year
        data_type: int64
        description: ""

      - name: fire_number
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: forest_area_code
        data_type: string
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('known_forest_area_codes') }}"
              quote: true
              severity: warn

      - name: fire_name
        data_type: string
        description: ""

      - name: current_size
        data_type: float64
        description: ""
        tests:
          - not_null:
              severity: warn

      - name: size_class
        data_type: string
        description: ""
        tests:
          - accepted_values:
              values: "{{ var('know_size_classes') }}"
              quote: true
              severity: error

      - name: fire_location_latitude
        data_type: float64
        description: ""

      - name: fire_location_longitude
        data_type: float64
        description: ""

      - name: fire_location_formatted
        data_type: string
        description: ""

      - name: fire_origin
        data_type: string
        description: ""

      - name: general_cause_desc
        data_type: string
        description: ""

      - name: industry_identifier_desc
        data_type: string
        description: ""

      - name: responsible_group_desc
        data_type: string
        description: ""

      - name: activity_class
        data_type: string
        description: ""

      - name: true_cause
        data_type: string
        description: ""

      - name: fire_start_date
        data_type: string
        description: ""

      - name: det_agent
        data_type: string
        description: ""

      - name: det_agent_type
        data_type: string
        description: ""

      - name: discovered_date
        data_type: string
        description: ""

      - name: discovered_size
        data_type: int64
        description: ""

      - name: reported_date
        data_type: string
        description: ""

      - name: dispatched_resource
        data_type: string
        description: ""

      - name: dispatch_date
        data_type: string
        description: ""

      - name: start_for_fire_date
        data_type: string
        description: ""

      - name: assessment_resource
        data_type: string
        description: ""

      - name: assessment_datetime
        data_type: string
        description: ""

      - name: assessment_hectares
        data_type: string
        description: ""

      - name: fire_spread_rate
        data_type: string
        description: ""

      - name: fire_type
        data_type: string
        description: ""

      - name: fire_position_on_slope
        data_type: string
        description: ""

      - name: weather_conditions_over_fire
        data_type: string
        description: ""

      - name: temperature
        data_type: string
        description: ""

      - name: relative_humidity
        data_type: string
        description: ""

      - name: wind_direction
        data_type: string
        description: ""

      - name: wind_speed
        data_type: string
        description: ""

      - name: fuel_type
        data_type: string
        description: ""

      - name: initial_action_by
        data_type: string
        description: ""

      - name: ia_arrival_at_fire_date
        data_type: string
        description: ""

      - name: ia_access
        data_type: string
        description: ""

      - name: fire_fighting_start_date
        data_type: string
        description: ""

      - name: fire_fighting_start_size
        data_type: string
        description: ""

      - name: bucketing_on_fire
        data_type: string
        description: ""

      - name: distance_from_water_source
        data_type: string
        description: ""

      - name: first_bucket_drop_date
        data_type: string
        description: ""

      - name: bh_fs_date
        data_type: string
        description: ""

      - name: bh_hectares
        data_type: string
        description: ""

      - name: uc_fs_date
        data_type: string
        description: ""

      - name: uc_hectares
        data_type: string
        description: ""

      - name: to_fs_date
        data_type: string
        description: ""

      - name: to_hectares
        data_type: string
        description: ""

      - name: ex_fs_date
        data_type: string
        description: ""

      - name: ex_hectares
        data_type: string
        description: ""
   