
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_wildfires'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_wildfires'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_wildfires:
    wildfires_historic_dataset:
        fact_historical_fires:
          schema: wildfires_historic_dataset

    wildfires_active_dataset:
      fact_active_fires:
        schema: wildfires_active_dataset

    staging:
      # dim_wildfire_active_stage_of_control:
      #   schema: wildfires_active_dataset
      # dim_wildfire_historical_number:
      #   schema: wildfires_historic_dataset
      stg_staging__active:
        schema: wildfires_active_dataset
      stg_staging__historic:
        schema: wildfires_historic_dataset
      
      

vars:
  known_forest_area_codes: ['C', 'E', 'H', 'G', 'L', 'M', 'P', 'R', 'S', 'W']
  know_size_classes: ['A', 'B', 'C', 'D', 'E']
