version: 2

models:
  - name: fact_historical_fires
    description: ""
    columns:
      - name: fire_id
        data_type: string
        description: ""

      - name: fire_year
        data_type: int64
        description: ""

      - name: fire_number
        data_type: string
        description: ""

      - name: forest_area_code
        data_type: string
        description: ""

      - name: fire_name
        data_type: string
        description: ""

      - name: current_size
        data_type: float64
        description: ""

      - name: size_class
        data_type: string
        description: ""

      - name: fire_location_latitude
        data_type: float64
        description: ""

      - name: fire_location_longitude
        data_type: float64
        description: ""

      - name: fire_location_formatted
        data_type: string
        description: ""

      - name: fire_origin
        data_type: string
        description: ""

      - name: general_cause_desc
        data_type: string
        description: ""

      - name: industry_identifier_desc
        data_type: string
        description: ""

      - name: responsible_group_desc
        data_type: string
        description: ""

      - name: activity_class
        data_type: string
        description: ""

      - name: true_cause
        data_type: string
        description: ""

      - name: fire_start_date
        data_type: string
        description: ""

      - name: det_agent
        data_type: string
        description: ""

      - name: det_agent_type
        data_type: string
        description: ""

      - name: discovered_date
        data_type: string
        description: ""

      - name: discovered_size
        data_type: int64
        description: ""

      - name: reported_date
        data_type: string
        description: ""

      - name: dispatched_resource
        data_type: string
        description: ""

      - name: dispatch_date
        data_type: string
        description: ""

      - name: start_for_fire_date
        data_type: string
        description: ""

      - name: assessment_resource
        data_type: string
        description: ""

      - name: assessment_datetime
        data_type: string
        description: ""

      - name: assessment_hectares
        data_type: string
        description: ""

      - name: fire_spread_rate
        data_type: string
        description: ""

      - name: fire_type
        data_type: string
        description: ""

      - name: fire_position_on_slope
        data_type: string
        description: ""

      - name: weather_conditions_over_fire
        data_type: string
        description: ""

      - name: temperature
        data_type: string
        description: ""

      - name: relative_humidity
        data_type: string
        description: ""

      - name: wind_direction
        data_type: string
        description: ""

      - name: wind_speed
        data_type: string
        description: ""

      - name: fuel_type
        data_type: string
        description: ""

      - name: initial_action_by
        data_type: string
        description: ""

      - name: ia_arrival_at_fire_date
        data_type: string
        description: ""

      - name: ia_access
        data_type: string
        description: ""

      - name: fire_fighting_start_date
        data_type: string
        description: ""

      - name: fire_fighting_start_size
        data_type: string
        description: ""

      - name: bucketing_on_fire
        data_type: string
        description: ""

      - name: distance_from_water_source
        data_type: string
        description: ""

      - name: first_bucket_drop_date
        data_type: string
        description: ""

      - name: bh_fs_date
        data_type: string
        description: ""

      - name: bh_hectares
        data_type: string
        description: ""

      - name: uc_fs_date
        data_type: string
        description: ""

      - name: uc_hectares
        data_type: string
        description: ""

      - name: to_fs_date
        data_type: string
        description: ""

      - name: to_hectares
        data_type: string
        description: ""

      - name: ex_fs_date
        data_type: string
        description: ""

      - name: ex_hectares
        data_type: string
        description: ""

      - name: wildfire_number
        data_type: string
        description: ""

      - name: forest_area
        data_type: string
        description: ""

  - name: dim_wildfire_historical_number
    description: ""
    columns:
      - name: wildfire_number
        data_type: string
        description: ""

      - name: forest_area
        data_type: string
        description: ""

  - name: dim_wildfire_active_stage_of_control
    description: ""
    columns:
      - name: stage
        data_type: string
        description: ""

      - name: description
        data_type: string
        description: ""